### ISSUE TITLE
Running browser on a different computer from the app doesn't seem to work

### ISSUE THREAD

**Issue by dhylands** [fxbox/app#51] opened 2016-04-04 16:51 UTC
My foxbox is running on 192.168.0.24.
I do a cargo run on from that computer
I run the app using gulp from that computer

If I connect using http://localhost:8000 from that computer I get a splash
If I connect using http://192.168.0.24:8000 from that computer or another computer I get an "unable to connect"

**Comment by michielbdejong** [comment] 2016-04-07 04:02
This is by design; instead of using `gulp` to run the webserver, try:

```bash
HOSTNAME=0.0.0.0 gulp
```

**Comment by michielbdejong** [comment] 2016-04-09 12:21
@dhylands does that answer your question? Can this issue be closed?

**Comment by dhylands** [comment] 2016-04-09 18:52
Sure - but why isn't this the default? (HOSTNAME=0.0.0.0) I don't understand how the user is going to run the UI since they're not going be running the app server on their computers.

**Comment by michielbdejong** [comment] 2016-04-11 01:16
@dhylands remember that this app, and the registration-/dns-/tunnel-server it relies on, are going to be centralized services, whose Mozilla-hosted URL will be whitelisted in each Box that's shipped.

*Users* will not use gulp to run the app's webserver. They will just visit a Mozilla-controlled URL with their browser of choice, where they will see the content, like https://fxbox.github.io/app/#. Ops will probably also not use gulp for hosting the content of this app in production, but rather something like nginx, probably with a CDN in front.

So `gulp` is only for development. Feel free though to change it to `0.0.0.0` if you think it avoids confusion! :)

**Comment by azasypkin** [comment] 2016-04-20 09:24
So it looks like we can close this issue, @dhylands please reopen if you think we should fix anything here.

**Closed by azasypkin** 2016-04-20 09:24 UTC
