### ISSUE TITLE
Cannot remove and add recipe with the same name

### ISSUE THREAD

**Issue by isabelrios** [fxbox/app#86] opened 2016-04-14 15:35 UTC
Created a recipe 'Everyday in the evening, Camera take a picture'
Then I removed it with the 'x' button
I tried to create it again but was not able, I click on Done and although I taken back to the recipe list view it is not added and got this error in foxbox:

(this log is since I start creating it for the fist time)
[2016-04-14 17:31:11.098] INFO  Thinkerbell: Starting compilation of script 'Everyday in the evening, Camera take a picture.'
[2016-04-14 17:31:11.098] INFO  Thinkerbell: Starting execution of script 'Everyday in the evening, Camera take a picture.'
[2016-04-14 17:31:11.100] INFO  Added Thinkerbell Rule for 'Everyday in the evening, Camera take a picture.'
[2016-04-14 17:31:20.583] INFO  Removed Thinkerbell Rule for 'Everyday in the evening, Camera take a picture.'
[2016-04-14 17:31:38.342] INFO  Thinkerbell: Starting compilation of script 'Everyday in the evening, Camera take a picture.'
[2016-04-14 17:31:38.343] INFO  Thinkerbell: Starting execution of script 'Everyday in the evening, Camera take a picture.'
[2016-04-14 17:31:38.345] INFO  No need to add new ThinkerbellRule; ID 'Everyday in the evening, Camera take a picture.' already exists.

**Comment by azasypkin** [comment] 2016-04-19 12:47
Hey @isabelrios are still able to reproduce this issue?

**Comment by isabelrios** [comment] 2016-04-19 12:56
@azasypkin , Just checked and now seems to be working fine :) Closing the issue.
Thanks!

**Comment by isabelrios** [comment] 2016-04-19 15:15
Sorry @azasypkin I am still seeing this problem.
I can delete the recipe, but I cannot create it again, so seems like it is not fully removed. Maybe I should change the title as it could be confusing

**Comment by azasypkin** [comment] 2016-04-19 15:16
Haha, I've just noticed it! I believe it's taxonomy issue, but I'll investigate, thanks for reporting!

**Comment by azasypkin** [comment] 2016-04-20 08:42
Hey @Yoric is it something known?

To reproduce the issue, you just need to create Rule, then remove it and try to create it again (the same one). On the last step we receive  ```[thinkerbell@link.mozilla.org] No need to create a new service for this rule; ID 'Motion Sensor detects motion, say "Good morning!".' already exists.```

Also as a rule name we use sentence-like string ```Motion Sensor detects motion, say "Good morning!``` - I was surprised to see that it's used as an ID :)

**Comment by Yoric** [comment] 2016-04-20 09:16
Deflecting to @mcav, who wrote the adapter. I think that this warning on the console reveals a small issue (we apparently forget to take down the service when we remove the rule), but that shouldn't cause any real issue.

**Comment by azasypkin** [comment] 2016-04-20 09:49
> but that shouldn't cause any real issue.

Well, it causes the issue for the app, since foxbox doesn't return anything (via services request), neither old removed rule nor the new one we tried to add.

**Comment by Yoric** [comment] 2016-04-20 09:54
What do you mean "services request"?

**Comment by azasypkin** [comment] 2016-04-20 10:00
I mean we use the following request to get list of recipes:

POST http://local.97395dc612c4c2fba487a12525734206268aadfd.box.knilxof.org:3000/api/v1/services
{"getters":[{"kind":"ThinkerbellRuleSource"}]}

And it doesn't return anything (until you restart foxbox)

**Comment by azasypkin** [comment] 2016-04-27 07:20
https://github.com/fxbox/foxbox/pull/436 has just landed, so the issue should be fixed on the latest foxbox master.

@isabelrios please reopen if it still doesn't work for you.

**Closed by azasypkin** 2016-04-27 07:20 UTC
Labels: bug

**Comment by isabelrios** [comment] 2016-04-27 11:18
So far I see it working fine
Thanks!
